name: Check file size
on:               # or directly `on: [push]` to run the action on every push on any branch
  pull_request:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:     
  contents: read   # Grants read access to repository contents
  pull-requests: write  # Add this to ensure the workflow can access pull request resources

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check large files
        uses: ActionsDesk/lfs-warning@v3.2
        with:
          filesizelimit: 10485760 # this is 10MB so we can sync to HF Spaces